# Generated by Django 4.1.5 on 2023-01-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file_parser", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UploadFile",
            new_name="FileUpload",
        ),
        migrations.RenameField(
            model_name="fileupload",
            old_name="cnab_file",
            new_name="file_parser",
        ),
    ]
