# Generated by Django 4.1.5 on 2023-01-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_parser", "0002_rename_uploadfile_fileupload_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="file_parser",
            field=models.FileField(upload_to=""),
        ),
    ]
