# Generated by Django 4.1.5 on 2023-01-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_parser", "0005_alter_fileparsermodel_valor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileparsermodel",
            name="valor",
            field=models.IntegerField(),
        ),
    ]
